### ISSUE TITLE
想知道sEEG电极植入那张图是怎么画的

### ISSUE THREAD

**Issue by reasonllh** [liulab-repository/Du-IN#1]
想知道sEEG电极植入那张图是怎么画的，谢谢回答
<img width="391" alt="1734953561538" src="https://github.com/user-attachments/assets/39652889-824d-4234-931b-12a09b978b81" />

**Comment by NorbertZheng** [comment]
十分感谢对我们工作的关注！

BrainNet Viewer
北师大贺永组做的工具包
