### ISSUE TITLE
实验复现

### ISSUE THREAD

**Issue by lyyi599** [liulab-repository/Du-IN#2]
作者您好！
感谢您的工作，流程非常完整，实验也非常有启发。在复现实验的过程中遇到一点问题，在下游数据上的X_s和X_n是指的什么？给的hf的data中似乎没有这个数据，是如何得到的呢？
参见： https://github.com/liulab-repository/Du-IN/blob/a7bdb0422e5b9f32269547ee26934e8ad35f6977/utils/data/seeg/he2023xuanwu/word_recitation.py#L172
再次感谢！

**Comment by NorbertZheng** [comment]
十分感谢对我们工作的关注！

我们目前只提供了`X_s`，也就是双极参考后的数据（`A1-A2`）。`X_n`是对应的`A1+A2`，`X_s+X_n`就可以还原出原始的信号。但考虑到保护病人隐私，我们没有提供`X_n`和对应的MNI坐标，大部分模型（除去LaBram-Popt）都只用到了`X_s`，主要结论以及大部分基线模型复现是没有问题的。同时，与同期工作[seegnificant](https://gmentz.github.io/seegnificant)的结论一致，MNI坐标对于解码认知任务可能无法提供很大性能提升。
![image](https://github.com/user-attachments/assets/4152c078-8bfc-4135-9352-fc44dcdae779)

**Comment by lyyi599** [comment]
感谢回复，非常清晰。另还有两个问题想向您讨教一下：
1. 文中对通道选择的表述为“For each subject, after training the Du-IN model (with random initialization) on the downstream dataset, we utilize the weights W ∈ RC×D of linear projection in the spatial encoder to calculate the contribution scores S of channels”，也就是使用全部通道进行了pretrain后，在下游任务上finetune，再去进行选择通道的。而代码中训练vqvae的过程（从最开始读取数据）就预先定义了选择的通道，这里和原文表述有出入，方便进一步解释一下吗？
2. 对于数据的preprocessing，原文中4.2节preprocess中提到使用了“bi-polar re-referenced”（如您所说，X_s就已经读取双极参考的数值了），这样得到的结果应该是通道之间的差值。那么如何确定到底是哪个通道最重要呢？另外在代码中观察到，直接使用了通道名称的下标作为索引，这是直接将A1的下标当作A2-A1了吗？
再次感谢您的回复；）

**Comment by NorbertZheng** [comment]
1. 这一步是在所有模型评估之前的通道筛选，独立于下游任务的评估，可以看到所报的性能和主表中有差异。所有的模型都在筛选完通道之后，进行训练（和预训练，如果有的话）。至于基石模型，我们看了全部通道预训练的结果（与BrainBERT、Brant、LaBram等模型的评估方式对齐），没有显著提升。
3. 对直接拿`A1`的名字和MNI坐标指代`A1-A2`了，当然更精确的做法是拿`A1`和`A2`的MNI坐标均值来指代，但对于神经科学分析结果来说，影响不大。

**Comment by lyyi599** [comment]
非常清晰，恭喜中稿，感谢详细回复！
